In [1]:
import pandas as pd
import numpy as np

In [2]:
cd "c:\\work stuff\\Projects\\Credit Scoring Project\\Insurance-Credit-Scoring\\Data\\raw_data"

c:\work stuff\Projects\Credit Scoring Project\Insurance-Credit-Scoring\Data\raw_data

# LIFE INSURANCE

In [40]:
### only works for 2019 to 2017 since they were already in excel format
files= ["2019 Annual Insurance Industry Statistics.xlsm","2018 Annual Statistics 28062019.xls","2017-Annual-Insurance-Statistics-Uploaded.xlsm"]
new_df= pd.DataFrame()
c=0
for fil in files:
    c+=1
    f1 = pd.ExcelFile(fil)
    ## reading the specific sheets
    sheet1= pd.read_excel(f1,"APPENDIX 4 I",header=3)
    sheet2 = pd.read_excel(f1,"APPENDIX 4 II",header=3)
    sheet3 = pd.read_excel(f1,"APPENDIX 4 III",header=4)
    ### dropping the unnamed column
    sheet1.drop("Unnamed: 0",axis=1,inplace=True)
    sheet2.drop("Unnamed: 0",axis=1,inplace=True)
    sheet3.drop("Unnamed: 0",axis=1,inplace=True)
    ### setting the df index
    sheet1.set_index("Company",inplace=True)
    sheet2.set_index("Company",inplace=True)
    sheet3.set_index("Company",inplace=True)

    ### concatinating the data sheets
    new_df = pd.concat([new_df,sheet1.T,sheet2.T,sheet3.T])

In [41]:
new_df.head()

Company,Share Capital,Share Premium_x000D_\n,Revaluation Reserves,Statutory Reserves,Retained Earnings,Other Reserves,Total Equity_x000D_\n,Underwriting Provisions,Actuarial Contract Liabilities,LongTerm Liabilities,...,Term Deposits,Cash and Cash Balances,Outstanding Premiums,Other Receivables,Other Assets,Intangible Assets,Total Assets,Amounts in thousand Shillings,Amounts in thousand Shillings,Amounts in Thousand Shillings
ABSA LIFE ASSURANCE KENYA,699000.0,0.0,0.0,258704.0,0.0,0.0,957704.0,0.0,2060156.0,0.0,...,201697.0,21123.0,58731.0,89572.0,470006.0,0.0,4059547.0,NaN,NaN,NaN
APA LIFE ASSURANCE COMPANY,700000.0,0.0,0.0,82879.0,-165962.0,0.0,616918.0,110981.0,4996207.0,28550.0,...,964305.0,29655.0,140762.0,45911.0,71827.0,0.0,5964926.0,NaN,NaN,NaN
BRITAM LIFE ASSURANCE,400000.0,0.0,0.0,0.0,0.0,9408044.0,9808044.0,475696.0,71998988.0,3735019.0,...,1311185.0,61657.0,628241.0,1213704.0,11668051.0,1041664.0,87746623.0,NaN,NaN,NaN
CAPEX LIFE ASSURANCE COMPANY,345000.0,0.0,1613.0,-32014.0,0.0,823.0,315422.0,6240.0,505467.0,0.0,...,5000.0,31725.0,72824.0,0.0,35495.0,3441.0,878929.0,NaN,NaN,NaN
CIC LIFE ASSURANCE COMPANY,800000.0,0.0,0.0,1123620.0,71861.0,17401.0,2012883.0,597944.0,10936927.0,482814.0,...,1478296.0,158713.0,661651.0,443907.0,710408.0,2611.0,14695187.0,NaN,NaN,NaN

In [42]:
len(new_df.columns)

37

In [43]:
new_df.to_csv("Life_BS_19_17.csv")

### pdfs converted to excel

In [44]:
page_list15 = []
for i in range(59,62):
    page_list15.append("Table "+str(i))

In [45]:
page_list16 = []
for i in range(63,66):
    page_list16.append("Table "+str(i))

In [46]:
page_list14 = []
for i in range(32,35):
    page_list14.append("Table "+str(i))

In [47]:
page_list13 = []
for i in range(36,39):
    page_list13.append("Table "+str(i))

In [48]:
files2= ["Annual-_Industry_Report_2016.xlsx","Annual Report 2015.xlsx","Annual-Report-2014-12.10.2015-Final.xlsx","Latest 2013 IRA Annual Report.xlsx"]
pages=[page_list16,page_list15,page_list14,page_list13]
c=1
new_df2= pd.DataFrame()
for filz,page in zip(files2,pages):
    f2 = pd.ExcelFile(filz)
    ## reading the specific sheets
    for p in page:
        try:
            sheet=  pd.read_excel(f2,p,header=1)
            sheet.columns=sheet.columns.str.upper()
            
            sheet.set_index("COMPANY",inplace=True)
            sheet_t = sheet.T
            sheet_t.columns = sheet_t.columns.str.strip()
            new_df2 = pd.concat([new_df2,sheet_t])
        except KeyError:
            sheet=  pd.read_excel(f2,p,header=2)
            sheet.columns=sheet.columns.str.upper()
            sheet.columns=sheet.columns.str.upper()
            
            sheet.set_index("COMPANY",inplace=True)
            sheet_t = sheet.T
            sheet_t.columns = sheet_t.columns.str.strip()
            new_df2 = pd.concat([new_df2,sheet_t])
            
            print(sheet_t.columns)
            #c+=1

Index(['Share Capital', 'Share Premium', 'Revaluation Reserves',
       'Statutory Reserves', 'Retained Earnings', 'Other Reserves',
       'Total Equity', 'Underwriting Provisions',
       'Actuarial Contract Liabilities', 'LongTerm Liabilities',
       'Current Liabilities', 'Total Equity And Liabilities',
       'Land And Buildings', 'Investment Property', 'Other Fixed Assets',
       'Government Securities', 'Other Securities',
       'Investment in Related Companies', 'Corporate Bonds',
       'Commercial Papers', 'Debentures', 'Ordinary Shares Quoted',
       'Ordinary Shares Unquoted', 'Preference Shares Quoted',
       'Preference Shares Unquoted', 'Loans Secured & Unsecured', 'Mortgages',
       'Term Deposits', 'Cash and Cash Balances', 'Outstanding Premiums',
       'Other Receivables', 'Other Assets', 'Intangible Assets',
       'Total Assets',
       'Amounts in thousand Shillings                                                                                                                                                                                                                                                                                                    Continued next page'],
      dtype='object', name='COMPANY')
Index(['Share Capital', 'Share Premium', 'Revaluation Reserves',
       'Statutory Reserves', 'Retained Earnings', 'Other Reserves',
       'Total Equity', 'Underwriting Provisions',
       'Actuarial Contract Liabilities', 'LongTerm Liabilities',
       'Current Liabilities', 'Total Equity And Liabilities',
       'Land And Buildings', 'Investment Property', 'Other Fixed Assets',
       'Government Securities', 'Other Securities',
       'Investment in Related Companies', 'Corporate Bonds',
       'Commercial Papers', 'Debentures', 'Ordinary Shares Quoted',
       'Ordinary Shares Unquoted', 'Preference Shares Quoted',
       'Preference Shares Unquoted', 'Loans Secured & Unsecured', 'Mortgages',
       'Term Deposits', 'Cash and Cash Balances', 'Outstanding Premiums',
       'Other Receivables', 'Other Assets', 'Intangible Assets',
       'Total Assets', 'Amounts in Thousand Shillings'],
      dtype='object', name='COMPANY')
Index(['Share Capital', 'Share Premium', 'Revaluation Reserves',
       'Statutory Reserves', 'Retained Earnings', 'Other Reserves',
       'Total Equity', 'Underwriting Provisions',
       'Actuarial Contract Liabilities', 'LongTerm Liabilities',
       'Current Liabilities', 'Total Equity And Liabilities',
       'Land And Buildings', 'Investment Property', 'Other Fixed Assets',
       'Government Securities', 'Other Securities',
       'Investment in Related Companies', 'Corporate Bonds',
       'Commercial Papers', 'Debentures', 'Ordinary Shares Quoted',
       'Ordinary Shares Unquoted', 'Preference Shares Quoted',
       'Preference Shares Unquoted', 'Loans Secured & Unsecured', 'Mortgages',
       'Term Deposits', 'Cash and Cash Balances', 'Outstanding Premiums',
       'Other Receivables', 'Other Assets', 'Intangible Assets',
       'Total Assets',
       'Amounts in thousand Shillings                                                                                                                                                                                                                                                                                                    Continued next page'],
      dtype='object', name='COMPANY')
Index(['Share Capital', 'Share Premium', 'Revaluation Reserves',
       'Statutory Reserves', 'Retained Earnings', 'Other Reserves',
       'Total Equity', 'Underwriting Provisions',
       'Actuarial Contract Liabilities', 'LongTerm Liabilities',
       'Current Liabilities', 'Total Equity And Liabilities',
       'Land And Buildings', 'Investment Property', 'Other Fixed Assets',
       'Government Securities', 'Other Securities',
       'Investment in Related Companies', 'Corporate Bonds',
       'Commercial Papers', 'Debentures', 'Ordinary Shares Quoted',
       'Ordinary Shares Unquoted', 'Preference Shares Quoted',
       'Preference Shares Unquoted', 'Loans Secured & Unsecured', 'Mortgages',
       'Term Deposits', 'Cash and Cash Balances', 'Outstanding Premiums',
       'Other Receivables', 'Other Assets', 'Intangible Assets',
       'Total Assets', 'Amounts in Thousand Shillings'],
      dtype='object', name='COMPANY')
Index(['Share Capital', 'Share Premium', 'Revaluation Reserves',
       'Statutory Reserves', 'Retained Earnings', 'Other Reserves',
       'Total Equity', 'Underwriting Provisions',
       'Actuarial Contract Liabilities', 'LongTerm Liabilities',
       'Current Liabilities', 'Total Equity And Liabilities',
       'Land And Buildings', 'Investment Property', 'Other Fixed Assets',
       'Government Securities', 'Other Securities',
       'Investment in Related Companies', 'Corporate Bonds',
       'Commercial Papers', 'Debentures', 'Ordinary Shares Quoted',
       'Ordinary Shares Unquoted', 'Preference Shares Quoted',
       'Preference Shares Unquoted', 'Loans Secured & Unsecured', 'Mortgages',
       'Term Deposits', 'Cash and Cash Balances', 'Outstanding Premiums',
       'Other Receivables', 'Other Assets', 'Intangible Assets',
       'Total Assets', 'Amounts in thousand Shillings'],
      dtype='object', name='COMPANY')
Index(['Share Capital', 'Share Premium', 'Revaluation Reserves',
       'Statutory Reserves', 'Retained Earnings', 'Other Reserves',
       'Total Equity', 'Underwriting Provisions',
       'Actuarial Contract Liabilities', 'LongTerm Liabilities',
       'Current Liabilities', 'Total Equity And Liabilities',
       'Land And Buildings', 'Investment Property', 'Other Fixed Assets',
       'Government Securities', 'Other Securities',
       'Investment in Related Companies', 'Corporate Bonds',
       'Commercial Papers', 'Debentures', 'Ordinary Shares Quoted',
       'Ordinary Shares Unquoted', 'Preference Shares Quoted',
       'Preference Shares Unquoted', 'Loans Secured & Unsecured', 'Mortgages',
       'Term Deposits', 'Cash and Cash Balances', 'Outstanding Premiums',
       'Other Receivables', 'Other Assets', 'Intangible Assets',
       'Total Assets', 'Amounts in Thousand Shillings'],
      dtype='object', name='COMPANY')

In [49]:
new_df2.head()

COMPANY,Share Capital,Share Premium,Revaluation Reserves,Statutory Reserves,Retained Earnings,Other Reserves,Total Equity,Underwriting Provisions,Actuarial Contract Liabilities,LongTerm Liabilities,...,Other Receivables,Other Assets,Intangible Assets,Total Assets,Amounts in thousand Shillings Continued next page,Amounts in thousand Shillings Continued next page,Amounts in Thousand Shillings,Amounts in thousand Shillings Continued next page,Amounts in thousand Shillings Continued next page,Amounts in thousand Shillings
APA LIFE\nASSURANCE COMPANY,"450,000",-,"4,106","7,840","( 89,451 )",-,"372,495","150,623","3,313,362","3,385",...,"33,015","13,179","15,551","3,979,418",NaN,NaN,NaN,NaN,NaN,NaN
BARCLAYS LIFE ASSURANCE,"450,000",-,"1,915","( 476,999 )","78,323",-,"53,239",-,"818,405","400,000",...,"4,359",757,-,"1,625,393",NaN,NaN,NaN,NaN,NaN,NaN
BRITAM LIFE ASSURANCE,"880,000",-,-,-,-,"7,837,962","8,717,962","753,071","39,046,506","3,359,126",...,"1,168,232","14,901,597","1,007,766","52,863,086",NaN,NaN,NaN,NaN,NaN,NaN
CANNON\nASSURANCE COMPANY,"150,000",-,-,"204,897",-,"461,946","816,843","54,289","617,169","131,120",...,-,"37,770","1,069","1,703,985",NaN,NaN,NaN,NaN,NaN,NaN
CAPEX LIFE\nASSURANCE COMPANY,"150,000",-,778,"45,023",-,"48,793","244,593","2,099","74,383","111,741",...,-,"1,129",-,"471,636",NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
new_df2.to_csv("Life_16_13.csv")

In [51]:
import re

### batch 3 2006-2009

In [52]:
page_list06 = []
for i in range(32,35):
    page_list06.append("Table "+str(i))

In [53]:
page_list07 = []
for i in range(40,43):
    page_list07.append("Table "+str(i))

In [54]:
page_list09 = []
for i in range(40,43):
    page_list09.append("Table "+str(i))

In [55]:
page_list10 = []
for i in range(34,36):
    page_list10.append("Table "+str(i))

In [56]:
page_list11 = []
for i in range(28,31):
    page_list11.append("Table "+str(i))

In [57]:
files3= ["Annual_Report_Year_2006.xlsx","2007 Annual Report.xlsx","2009 Annual Report.xlsx"]
pages3=[page_list06,page_list07,page_list09]
c=1
new_df3= pd.DataFrame()
for fil3,page in zip(files3,pages3):
    f3 = pd.ExcelFile(fil3)
    ## reading the specific sheets
    for p in page:
        try:
            sheet=  pd.read_excel(f3,p,header=1)
            sheet.columns=sheet.columns.str.upper()
            
            sheet.set_index("ITEM",inplace=True)
            sheet_t = sheet.T
            #sheet_t.columns = sheet_t.columns.str.strip()
            sheet_t.columns = sheet_t.columns.str.replace('\n',' ')
            sheet_t.columns = sheet_t.columns.str.replace(' ','_')
            sheet_t.columns = sheet_t.columns.str.replace('__','_')
            sheet_t.columns = sheet_t.columns.str.upper()
            new_df3 = pd.concat([new_df3,sheet_t])
        except KeyError:
            sheet=  pd.read_excel(f3,p,header=2)
            sheet.columns=sheet.columns.str.upper()
            sheet.set_index("ITEM",inplace=True)
            sheet_t = sheet.T
            #sheet_t.columns = sheet_t.columns.str.strip()
            sheet_t.columns = sheet_t.columns.str.replace('\n',' ')
            sheet_t.columns = sheet_t.columns.str.replace(' ','_')
            sheet_t.columns = sheet_t.columns.str.replace('__','_')
            sheet_t.columns = sheet_t.columns.str.upper()
            new_df3 = pd.concat([new_df3,sheet_t])
            
        print(len(sheet_t.columns))

33
33
33
33
33
33
34
34
34

In [58]:
new_df3.to_csv("Life_BS_09_06.csv")

### batch 4 bunched 2getha since they have more similar columns

In [59]:

files4= ["IRA ANNUAL REPORT 2011 FINAL.xlsx","2010 insurance industry report.xlsx"]
pages4=[page_list11,page_list10]
c=1
new_df4= pd.DataFrame()
for fil4,page in zip(files4,pages4):
    f4 = pd.ExcelFile(fil4)
    ## reading the specific sheets
    for p in page:
        try:
            sheet=  pd.read_excel(f4,p,header=1)
            sheet.columns=sheet.columns.str.upper()
            
            sheet.set_index("ITEM",inplace=True)
            sheet_t = sheet.T
            #sheet_t.columns = sheet_t.columns.str.strip()
            sheet_t.columns = sheet_t.columns.str.replace('\n',' ')
            sheet_t.columns = sheet_t.columns.str.replace(' ','_')
            sheet_t.columns = sheet_t.columns.str.replace('__','_')
            sheet_t.columns = sheet_t.columns.str.upper()
            new_df4 = pd.concat([new_df4,sheet_t])
        except KeyError:
            sheet=  pd.read_excel(f4,p,header=2)
            sheet.columns=sheet.columns.str.upper()
            sheet.set_index("ITEM",inplace=True)
            sheet_t = sheet.T
            #sheet_t.columns = sheet_t.columns.str.strip()
            sheet_t.columns = sheet_t.columns.str.replace('\n',' ')
            sheet_t.columns = sheet_t.columns.str.replace(' ','_')
            sheet_t.columns = sheet_t.columns.str.replace('__','_')
            sheet_t.columns = sheet_t.columns.str.upper()
            new_df4 = pd.concat([new_df4,sheet_t])
            
        print(len(sheet_t.columns))

35
35
35
36
36

In [60]:
new_df4.to_csv("Life_BS_11_10.csv")

### agregating P/L for life insurance firms

In [28]:
### only works for 2019 to 2017 since they were already in excel format

files= ["2019 Annual Insurance Industry Statistics.xlsm","2018 Annual Statistics 28062019.xls","2017-Annual-Insurance-Statistics-Uploaded.xlsm"]
p_l_b1= pd.DataFrame()
c=0
for fil in files:
    c+=1
    f1 = pd.ExcelFile(fil)
    ## reading the specific sheets
    sheet1= pd.read_excel(f1,"APPENDIX 2",header=3)
    ### dropping the unnamed column
    sheet1.drop("Unnamed: 0",axis=1,inplace=True)
    ### concatinating the data sheets
    p_l_b1 = pd.concat([p_l_b1,sheet1])

In [29]:
p_l_b1.to_csv("p_l_life_19_17.csv")

## P/L for pdf to excel converted files

In [88]:

files2= ["Annual-_Industry_Report_2016.xlsx","Annual Report 2015.xlsx","Annual-Report-2014-12.10.2015-Final.xlsx","Latest 2013 IRA Annual Report.xlsx"]
pages=[["Table 61"],["Table 57"],["Table 30"],["Table 34"]]
p_l_b2= pd.DataFrame()
for filz,page in zip(files2,pages):
    f2 = pd.ExcelFile(filz)
    ## reading the specific sheets
    for p in page:
        sheet=  pd.read_excel(f2,p,header=1)
        sheet.columns=sheet.columns.str.upper()
        sheet_t = sheet
        sheet_t.columns = sheet_t.columns.str.strip()
        p_l_b2 = pd.concat([p_l_b2,sheet_t])

In [92]:
p_l_b2.to_csv("p_l_b2_life_2016_2013.csv")

## P/L  batch 3 2011- 2006 agregate both gen and life insurance orgs

### 2006-2009

In [204]:
files3= ["Annual_Report_Year_2006.xlsx","2007 Annual Report.xlsx","2009 Annual Report.xlsx"]
pages3=[["Table 31"],["Table 38"],["Table 38"]]
c=1
p_l_b3= pd.DataFrame()
for fil3,page in zip(files3,pages3):
    f3 = pd.ExcelFile(fil3)
    ## reading the specific sheets
    for p in page:
        try:
            sheet=  pd.read_excel(f3,p,header=1)
            sheet.columns=sheet.columns.str.upper()
            
            sheet.set_index("NAME OF INSURER",inplace=True)
            sheet_t = sheet
            sheet_t.columns = sheet_t.columns.str.strip()
            sheet_t.columns = sheet_t.columns.str.replace('\n',' ')
            sheet_t.columns = sheet_t.columns.str.replace(' ','_')
            sheet_t.columns = sheet_t.columns.str.replace('__','_')
            sheet_t.columns = sheet_t.columns.str.upper()
            p_l_b3 = pd.concat([p_l_b3,sheet_t])
        except KeyError:
            sheet=  pd.read_excel(f3,p,header=3)
            # sheet.columns=sheet.columns.str.upper()
            #sheet.set_index("NAME OF INSURER",inplace=True)
            # sheet_t = sheet
            sheet_t.columns = sheet_t.columns.str.strip()
            sheet_t.columns = sheet_t.columns.str.replace('\n',' ')
            sheet_t.columns = sheet_t.columns.str.replace(' ','_')
            sheet_t.columns = sheet_t.columns.str.replace('__','_')
            sheet_t.columns = sheet_t.columns.str.upper()
            p_l_b3 = pd.concat([p_l_b3,sheet_t])
            
        print(sheet_t.columns)

Index(['NO.', 'PROFIT/LOSS_TRANSFERRED_FROM_REVENUE', 'INVESTMENT_INCOME',
       'SHARE_IN_MOTOR_POOL', 'OTHER_INCOMES', 'MANAGEMENT_EXPENSES',
       'OTHER_EXPENSES', 'PROVISION_FOR_TAXATION',
       'PROFIT_OR_LOSS_AFTER_TAXITION', 'UNAPPRTD_PROFIT/LOSS_B/F',
       'TOTAL_PROFIT_AVAILABLE_FOR_DISTRIBUTION', 'TRANSFERS_TO_RESERVES',
       'DIVIDENDS', 'OTHER_APPRTNS', 'UNAPPRTD_PROFIT/LOSS_C/F'],
      dtype='object')
Index(['NO.', 'PROFIT/LOSS_TRANSFERRED_FROM_REVENUE', 'INVESTMENT_INCOME',
       'SHARE_IN_MOTOR_POOL', 'OTHER_INCOMES', 'MANAGEMENT_EXPENSES',
       'OTHER_EXPENSES', 'PROVISION_FOR_TAXATION',
       'PROFIT_OR_LOSS_AFTER_TAXITION', 'UNAPPRTD_PROFIT/LOSS_B/F',
       'TOTAL_PROFIT_AVAILABLE_FOR_DISTRIBUTION', 'TRANSFERS_TO_RESERVES',
       'DIVIDENDS', 'OTHER_APPRTNS', 'UNAPPRTD_PROFIT/LOSS_C/F'],
      dtype='object')
Index(['NO.', 'PROFIT/LOSS_TRANSFERRED_FROM_REVENUE', 'INVESTMENT_INCOME',
       'SHARE_IN_MOTOR_POOL', 'OTHER_INCOMES', 'MANAGEMENT_EXPENSES',
       'OTHER_EXPENSES', 'PROVISION_FOR_TAXATION',
       'PROFIT_OR_LOSS_AFTER_TAXITION', 'UNAPPRTD_PROFIT/LOSS_B/F',
       'TOTAL_PROFIT_AVAILABLE_FOR_DISTRIBUTION', 'TRANSFERS_TO_RESERVES',
       'DIVIDENDS', 'OTHER_APPRTNS', 'UNAPPRTD_PROFIT/LOSS_C/F'],
      dtype='object')

In [206]:
p_l_b3.to_csv("p_l_life_2006_2009.csv")

## P/L for 2010 to 2011

In [261]:
files4= ["IRA ANNUAL REPORT 2011 FINAL.xlsx","2010 insurance industry report.xlsx"]
pages4=[["Table 26"],["Table 32"]]
c=1
p_l_11_10_df= pd.DataFrame()
for fil4,page in zip(files4,pages4):
    f4 = pd.ExcelFile(fil4)
    ## reading the specific sheets
    for p in page:
        try:

            sheet=  pd.read_excel(f4,p,header=1)
            sheet.columns=sheet.columns.str.upper()
            sheet.columns = sheet.columns.str.replace(' ','')
            sheet.set_index("COMPANY",inplace=True)
            sheet_t = sheet
            #sheet_t.columns = sheet_t.columns.str.strip()
            sheet_t.columns = sheet_t.columns.str.replace('\n',' ')
            sheet_t.columns = sheet_t.columns.str.replace(' ','_')
            sheet_t.columns = sheet_t.columns.str.replace('__','_')
            sheet_t.columns = sheet_t.columns.str.upper()
            #p_l_11_10_df = pd.concat([p_l_11_10_df,sheet_t])
        except KeyError:
            sheet=  pd.read_excel(f4,p,header=2)
            sheet.columns=sheet.columns.str.upper()
            sheet.set_index("COMPANY",inplace=True)
            sheet_t = sheet
            #sheet_t.columns = sheet_t.columns.str.strip()
            sheet_t.columns = sheet_t.columns.str.replace('\n',' ')
            sheet_t.columns = sheet_t.columns.str.replace(' ','_')
            sheet_t.columns = sheet_t.columns.str.replace('__','_')
            sheet_t.columns = sheet_t.columns.str.upper()
            p_l_11_10_df = pd.concat([p_l_11_10_df,sheet_t])
            
        print(sheet_t.columns)

Index(['UNNAMED:0', 'PROFIT/(LOSS)FROMREVENUE', 'INVESTMENTINCOME',
       'OTHERINCOMES', 'MANAGEMENTEXPENSES', 'OTHEREXPENSES',
       'PROFIT/(LOSS_)BEFORETAXATION', 'PROVISIONFORTAXATION',
       'PROFIT/(LOSS)AFTERTAXATION', 'UNAPPRT'DPROFIT/(LOSS)B/F',
       'TRANSFERTORESERVE', 'DIVIDEND', 'OTHERAPPRTNS',
       'UNAPPRRT'DPROFIT/(LOSS_)C/F'],
      dtype='object')
Index(['UNNAMED:_0', 'UNNAMED:_1', 'PROFIT/_(LOSS)_FROM_REVENUE',
       'INVESTMENT_INCOME', 'OTHER_INCOMES', 'MANAGEMENT_EXPENSES',
       'OTHER_EXPENSES', 'PROFIT/(LOSS)_BEFORE_TAXATION',
       'PROVISION_FOR_TAXATION', 'PROFIT/(LOSS)_AFTER_TAXA-_TION',
       'UNAPPRTâ€™D_PROFIT/(_LOSS)_B/F', 'TRANSFER_TO_RESERVE', 'DIVIDEND',
       'OTHER_AP-_PRTNS', 'UNAPPRRTâ€™D_PROFIT/(LOSS)_C/F'],
      dtype='object')

In [263]:
p_l_11_10_df.to_csv("p_l_11_10_life.csv")

# GENERAL INSURANCE

## 2019 -2017

In [230]:
### only works for 2019 to 2017 since they were already in excel format
files= ["2019 Annual Insurance Industry Statistics.xlsm","2018 Annual Statistics 28062019.xls","2017-Annual-Insurance-Statistics-Uploaded.xlsm"]
gen_df= pd.DataFrame()
c=0
for fil in files:
    c+=1
    f1 = pd.ExcelFile(fil)
    ## reading the specific sheets
    sheet1= pd.read_excel(f1,"APPENDIX 5 I",header=2)
    sheet2 = pd.read_excel(f1,"APPENDIX 5 II",header=4)
    sheet3 = pd.read_excel(f1,"APPENDIX 5 III",header=4)
    sheet4 = pd.read_excel(f1,"APPENDIX5 IV",header=4)
    ### dropping the unnamed column
    sheet1.drop("Unnamed: 0",axis=1,inplace=True)
    sheet2.drop("Unnamed: 0",axis=1,inplace=True)
    sheet3.drop("Unnamed: 0",axis=1,inplace=True)
    sheet4.drop("Unnamed: 0",axis=1,inplace=True)
    ### setting the df index
    sheet1.set_index("Company",inplace=True)
    sheet2.set_index("Company",inplace=True)
    sheet3.set_index("Company",inplace=True)
    sheet4.set_index("Company",inplace=True)

    # ### concatinating the data sheets
    gen_df = pd.concat([gen_df,sheet1.T,sheet2.T,sheet3.T])

In [232]:
gen_df.to_csv("General_19_17_b_l.csv")

## 2016 -2013

In [264]:
page_list16 = []
for i in range(66,70):
    page_list16.append("Table "+str(i))

In [265]:
page_list15 = []
for i in range(62,66):
    page_list15.append("Table "+str(i))

In [266]:
page_list14 = []
for i in range(35,39):
    page_list14.append("Table "+str(i))

In [267]:
page_list13 = []
for i in range(39,43):
    page_list13.append("Table "+str(i))

In [272]:
files2= ["Annual-_Industry_Report_2016.xlsx","Annual Report 2015.xlsx","Annual-Report-2014-12.10.2015-Final.xlsx","Latest 2013 IRA Annual Report.xlsx"]
pages=[page_list16,page_list15,page_list14,page_list13]
c=1
General_16_13_b_s= pd.DataFrame()
for filz,page in zip(files2,pages):
    f2 = pd.ExcelFile(filz)
    ## reading the specific sheets
    for p in page:
        try:
            sheet=  pd.read_excel(f2,p,header=1)
            sheet.columns=sheet.columns.str.upper()
            
            sheet.set_index("COMPANY",inplace=True)
            sheet_t = sheet.T
            sheet_t.columns = sheet_t.columns.str.strip()
            sheet_t.columns = sheet_t.columns.str.upper()
            General_16_13_b_s = pd.concat([General_16_13_b_s,sheet_t])
        except KeyError:
            sheet=  pd.read_excel(f2,p,header=2)
            sheet.columns=sheet.columns.str.upper()
            sheet.columns=sheet.columns.str.upper()
            
            sheet.set_index("COMPANY",inplace=True)
            sheet_t = sheet.T
            sheet_t.columns = sheet_t.columns.str.strip()
            sheet_t.columns = sheet_t.columns.str.upper()
            General_16_13_b_s = pd.concat([General_16_13_b_s,sheet_t])
            
            print(sheet_t.columns)

Index(['SHARE CAPITAL', 'SHARE PREMIUM', 'REVALUATION RESERVES',
       'STATUTORY RESERVES', 'RETAINED EARNINGS', 'OTHER RESERVES',
       'TOTAL EQUITY', 'UNDERWRITING PROVISIONS',
       'ACTUARIAL CONTRACT LIABILITIES', 'LONGTERM LIABILITIES',
       'CURRENT LIABILITIES', 'TOTAL EQUITY AND LIABILITIES',
       'LAND AND BUILDINGS', 'INVESTMENT PROPERTY', 'OTHER FIXED ASSETS',
       'GOVERNMENT SECURITIES', 'OTHER SECURITIES',
       'INVESTMENT IN RELATED COMPANIES', 'CORPORATE BONDS',
       'COMMERCIAL PAPERS', 'DEBENTURES', 'ORDINARY SHARES QUOTED',
       'ORDINARY SHARES UNQUOTED', 'PREFERENCE SHARES QUOTED',
       'PREFERENCE SHARES UNQUOTED', 'LOANS SECURED & UNSECURED', 'MORTGAGES',
       'TERM DEPOSITS', 'CASH AND CASH BALANCES', 'OUTSTANDING PREMIUMS',
       'OTHER RECEIVABLES', 'OTHER ASSETS', 'INTANGIBLE ASSETS',
       'TOTAL ASSETS',
       'AMOUNTS IN THOUSAND SHILLINGS                                                                                                                                                                                                                                                           CONTINUED NEXT PAGE'],
      dtype='object', name='COMPANY')
Index(['SHARE CAPITAL', 'SHARE PREMIUM', 'REVALUATION RESERVES',
       'STATUTORY RESERVES', 'RETAINED EARNINGS', 'OTHER RESERVES',
       'TOTAL EQUITY', 'UNDERWRITING PROVISIONS',
       'ACTUARIAL CONTRACT LIABILITIES', 'LONGTERM LIABILITIES',
       'CURRENT LIABILITIES', 'TOTAL EQUITY AND LIABILITIES',
       'LAND AND BUILDINGS', 'INVESTMENT PROPERTY', 'OTHER FIXED ASSETS',
       'GOVERNMENT SECURITIES', 'OTHER SECURITIES',
       'INVESTMENT IN RELATED COMPANIES', 'CORPORATE BONDS',
       'COMMERCIAL PAPERS', 'DEBENTURES', 'ORDINARY SHARES QUOTED',
       'ORDINARY SHARES UNQUOTED', 'PREFERENCE SHARES QUOTED',
       'PREFERENCE SHARES UNQUOTED', 'LOANS SECURED & UNSECURED', 'MORTGAGES',
       'TERM DEPOSITS', 'CASH AND CASH BALANCES', 'OUTSTANDING PREMIUMS',
       'OTHER RECEIVABLES', 'OTHER ASSETS', 'INTANGIBLE ASSETS',
       'TOTAL ASSETS',
       'AMOUNTS IN THOUSAND SHILLINGS                                                                                                                                                                                                                                                                      CONTINUED NEXT PAGE'],
      dtype='object', name='COMPANY')
Index(['SHARE CAPITAL', 'SHARE PREMIUM', 'REVALUATION RESERVES',
       'STATUTORY RESERVES', 'RETAINED EARNINGS', 'OTHER RESERVES',
       'TOTAL EQUITY', 'UNDERWRITING PROVISIONS',
       'ACTUARIAL CONTRACT LIABILITIES', 'LONGTERM LIABILITIES',
       'CURRENT LIABILITIES', 'TOTAL EQUITY AND LIABILITIES',
       'LAND AND BUILDINGS', 'INVESTMENT PROPERTY', 'OTHER FIXED ASSETS',
       'GOVERNMENT SECURITIES', 'OTHER SECURITIES',
       'INVESTMENT IN RELATED COMPANIES', 'CORPORATE BONDS',
       'COMMERCIAL PAPERS', 'DEBENTURES', 'ORDINARY SHARES QUOTED',
       'ORDINARY SHARES UNQUOTED', 'PREFERENCE SHARES QUOTED',
       'PREFERENCE SHARES UNQUOTED', 'LOANS SECURED & UNSECURED', 'MORTGAGES',
       'TERM DEPOSITS', 'CASH AND CASH BALANCES', 'OUTSTANDING PREMIUMS',
       'OTHER RECEIVABLES', 'OTHER ASSETS', 'INTANGIBLE ASSETS',
       'TOTAL ASSETS', 'AMOUNTS IN THOUSAND SHILLINGS'],
      dtype='object', name='COMPANY')
Index(['SHARE CAPITAL', 'SHARE PREMIUM', 'REVALUATION RESERVES',
       'STATUTORY RESERVES', 'RETAINED EARNINGS', 'OTHER RESERVES',
       'TOTAL EQUITY', 'UNDERWRITING PROVISIONS',
       'ACTUARIAL CONTRACT LIABILITIES', 'LONGTERM LIABILITIES',
       'CURRENT LIABILITIES', 'TOTAL EQUITY AND LIABILITIES',
       'LAND AND BUILDINGS', 'INVESTMENT PROPERTY', 'OTHER FIXED ASSETS',
       'GOVERNMENT SECURITIES', 'OTHER SECURITIES',
       'INVESTMENT IN RELATED COMPANIES', 'CORPORATE BONDS',
       'COMMERCIAL PAPERS', 'DEBENTURES', 'ORDINARY SHARES QUOTED',
       'ORDINARY SHARES UNQUOTED', 'PREFERENCE SHARES QUOTED',
       'PREFERENCE SHARES UNQUOTED', 'LOANS SECURED & UNSECURED', 'MORTGAGES',
       'TERM DEPOSITS', 'CASH AND CASH BALANCES', 'OUTSTANDING PREMIUMS',
       'OTHER RECEIVABLES', 'OTHER ASSETS', 'INTANGIBLE ASSETS',
       'TOTAL ASSETS',
       'AMOUNTS IN THOUSAND SHILLINGS                                                                                                                                                                                                                                                            CONTINUED NEXT PAGE'],
      dtype='object', name='COMPANY')
Index(['SHARE CAPITAL', 'SHARE PREMIUM', 'REVALUATION RESERVES',
       'STATUTORY RESERVES', 'RETAINED EARNINGS', 'OTHER RESERVES',
       'TOTAL EQUITY', 'UNDERWRITING PROVISIONS',
       'ACTUARIAL CONTRACT LIABILITIES', 'LONGTERM LIABILITIES',
       'CURRENT LIABILITIES', 'TOTAL EQUITY AND LIABILITIES',
       'LAND AND BUILDINGS', 'INVESTMENT PROPERTY', 'OTHER FIXED ASSETS',
       'GOVERNMENT SECURITIES', 'OTHER SECURITIES',
       'INVESTMENT IN RELATED COMPANIES', 'CORPORATE BONDS',
       'COMMERCIAL PAPERS', 'DEBENTURES', 'ORDINARY SHARES QUOTED',
       'ORDINARY SHARES UNQUOTED', 'PREFERENCE SHARES QUOTED',
       'PREFERENCE SHARES UNQUOTED', 'LOANS SECURED & UNSECURED', 'MORTGAGES',
       'TERM DEPOSITS', 'CASH AND CASH BALANCES', 'OUTSTANDING PREMIUMS',
       'OTHER RECEIVABLES', 'OTHER ASSETS', 'INTANGIBLE ASSETS',
       'TOTAL ASSETS',
       'AMOUNTS IN THOUSAND SHILLINGS                                                                                                                                                                                                                                                               CONTINUED NEXT PAGE'],
      dtype='object', name='COMPANY')
Index(['SHARE CAPITAL', 'SHARE PREMIUM', 'REVALUATION RESERVES',
       'STATUTORY RESERVES', 'RETAINED EARNINGS', 'OTHER RESERVES',
       'TOTAL EQUITY', 'UNDERWRITING PROVISIONS',
       'ACTUARIAL CONTRACT LIABILITIES', 'LONGTERM LIABILITIES',
       'CURRENT LIABILITIES', 'TOTAL EQUITY AND LIABILITIES',
       'LAND AND BUILDINGS', 'INVESTMENT PROPERTY', 'OTHER FIXED ASSETS',
       'GOVERNMENT SECURITIES', 'OTHER SECURITIES',
       'INVESTMENT IN RELATED COMPANIES', 'CORPORATE BONDS',
       'COMMERCIAL PAPERS', 'DEBENTURES', 'ORDINARY SHARES QUOTED',
       'ORDINARY SHARES UNQUOTED', 'PREFERENCE SHARES QUOTED',
       'PREFERENCE SHARES UNQUOTED', 'LOANS SECURED & UNSECURED', 'MORTGAGES',
       'TERM DEPOSITS', 'CASH AND CASH BALANCES', 'OUTSTANDING PREMIUMS',
       'OTHER RECEIVABLES', 'OTHER ASSETS', 'INTANGIBLE ASSETS',
       'TOTAL ASSETS', 'AMOUNTS IN THOUSAND SHILLINGS'],
      dtype='object', name='COMPANY')
Index(['SHARE CAPITAL', 'SHARE PREMIUM', 'REVALUATION RESERVES',
       'STATUTORY RESERVES', 'RETAINED EARNINGS', 'OTHER RESERVES',
       'TOTAL EQUITY', 'UNDERWRITING PROVISIONS',
       'ACTUARIAL CONTRACT LIABILITIES', 'LONGTERM LIABILITIES',
       'CURRENT LIABILITIES', 'TOTAL EQUITY AND LIABILITIES',
       'LAND AND BUILDINGS', 'INVESTMENT PROPERTY', 'OTHER FIXED ASSETS',
       'GOVERNMENT SECURITIES', 'OTHER SECURITIES',
       'INVESTMENT IN RELATED COMPANIES', 'CORPORATE BONDS',
       'COMMERCIAL PAPERS', 'DEBENTURES', 'ORDINARY SHARES QUOTED',
       'ORDINARY SHARES UNQUOTED', 'PREFERENCE SHARES QUOTED',
       'PREFERENCE SHARES UNQUOTED', 'LOANS SECURED & UNSECURED', 'MORTGAGES',
       'TERM DEPOSITS', 'CASH AND CASH BALANCES', 'OUTSTANDING PREMIUMS',
       'OTHER RECEIVABLES', 'OTHER ASSETS', 'INTANGIBLE ASSETS',
       'TOTAL ASSETS',
       'AMOUNTS IN THOUSAND SHILLINGS                                                                                                                                                                                                                                                                                                    CONTINUED NEXT PAGE'],
      dtype='object', name='COMPANY')

In [273]:
General_16_13_b_s.to_csv("General_bs_16_13.csv")

## 2006 - 2009

In [4]:
page_list06 = []
for i in range(32,35):
    page_list06.append("Table "+str(i))

In [15]:
page_list07 = []
for i in range(43,47):
    page_list07.append("Table "+str(i))

In [16]:
page_list10 = []
for i in range(36,40):
    page_list10.append("Table "+str(i))

In [9]:
files3= ["Annual_Report_Year_2006.xlsx","2007 Annual Report.xlsx","2009 Annual Report.xlsx"]
pages3=[page_list06,page_list07,page_list09]
c=1
General_BS_09_06_df= pd.DataFrame()
for fil3,page in zip(files3,pages3):
    f3 = pd.ExcelFile(fil3)
    ## reading the specific sheets
    for p in page:
        try:
            sheet=  pd.read_excel(f3,p,header=1)
            sheet.columns=sheet.columns.str.upper()
            
            sheet.set_index("ITEM",inplace=True)
            sheet_t = sheet.T
            #sheet_t.columns = sheet_t.columns.str.strip()
            sheet_t.columns = sheet_t.columns.str.replace('\n',' ')
            sheet_t.columns = sheet_t.columns.str.replace(' ','_')
            sheet_t.columns = sheet_t.columns.str.replace('__','_')
            sheet_t.columns = sheet_t.columns.str.upper()
            General_BS_09_06_df = pd.concat([General_BS_09_06_df,sheet_t])
        except KeyError:
            sheet=  pd.read_excel(f3,p,header=2)
            sheet.columns=sheet.columns.str.upper()
            sheet.set_index("ITEM",inplace=True)
            sheet_t = sheet.T
            #sheet_t.columns = sheet_t.columns.str.strip()
            sheet_t.columns = sheet_t.columns.str.replace('\n',' ')
            sheet_t.columns = sheet_t.columns.str.replace(' ','_')
            sheet_t.columns = sheet_t.columns.str.replace('__','_')
            sheet_t.columns = sheet_t.columns.str.upper()
            General_BS_09_06_df = pd.concat([General_BS_09_06_df,sheet_t])
            
        print(len(sheet_t.columns))

33
33
33
33
33
33
33
33
34
34
34
34

In [14]:
General_BS_09_06_df.to_csv("General_BS_09_06.csv")

## 2011 and 2010

In [142]:
page_list10 = []
for i in range(36,40):
    page_list10.append("Table "+str(i))

In [3]:
page_list11 = []
for i in range(31,35):
    page_list11.append("Table "+str(i))

In [169]:
files4= ["2010 insurance industry report.xlsx"]
pages4=[page_list10]
c=1
new_df4= pd.DataFrame()
for fil4,page in zip(files4,pages4):
    f4 = pd.ExcelFile(fil4)
    ## reading the specific sheets
    for p in page:
        try:
            sheet=  pd.read_excel(f4,p,header=1)
            sheet.columns=sheet.columns.str.upper()
            
            sheet.set_index("ITEM",inplace=True)
            sheet_t = sheet.T
            #sheet_t.columns = sheet_t.columns.str.strip()
            sheet_t.columns = sheet_t.columns.str.replace('\n',' ')
            sheet_t.columns = sheet_t.columns.str.replace(' ','_')
            sheet_t.columns = sheet_t.columns.str.replace('__','_')
            sheet_t.columns = sheet_t.columns.str.upper()
            sheet_t.index = sheet_t.index.str.replace('\n',' ')
            sheet_t.index = sheet_t.index.str.replace(' ','_')
            sheet_t.index = sheet_t.index.str.replace('__','_')
            #sheet_t.reset_index(inplace=True)
            #print(sheet_t.index)
            new_df4 = pd.concat([new_df4,sheet_t])
        except( KeyError, IndexError)as e:
            sheet=  pd.read_excel(f4,p,header=2)
            sheet.columns=sheet.columns.str.upper()
            sheet.set_index("ITEM",inplace=True)
            sheet_t = sheet.T
            #sheet_t.columns = sheet_t.columns.str.strip()
            sheet_t.index = sheet_t.index.str.replace('-',' ')
            sheet_t.columns = sheet_t.columns.str.replace('\n',' ')
            sheet_t.columns = sheet_t.columns.str.replace(' ','_')
            sheet_t.columns = sheet_t.columns.str.replace('__','_')
            sheet_t.columns = sheet_t.columns.str.upper()
            sheet_t.index = sheet_t.index.str.replace('-',' ')
            sheet_t.index = sheet_t.index.str.replace('\n',' ')
            sheet_t.index = sheet_t.index.str.replace(' ','_')
            sheet_t.index = sheet_t.index.str.replace('__','_')
            new_df4 = pd.concat([new_df4,sheet_t])
        print(sheet_t.index)
            
        #print(len(sheet_t.columns))

Index(['NO.', 'UNNAMED:_1', 'CHARTIS_(K)', 'AMACO', 'APA', 'BLUE_SSHIELD',
       'BRITAK', 'CANNON', 'CFC_LIFE', 'CON_CORD', 'COOP_ERATIVE',
       'CORPO_RATE'],
      dtype='object')
Index(['NO.', 'UNNAMED:_1', 'DIRECTLINE', 'EAST_AFRICA_RE', 'FIDELITY_SHIELD',
       'FIRST_ASSURANCE', 'GATEWAY', 'GEMINIA', 'GA', 'HERITAGE', 'ICEA',
       'INTRA_AFRICA'],
      dtype='object')
Index(['NO.', 'UNNAMED:_1', 'INVES_CO', 'JUBILEE', 'KENIN_DIA', 'KENYA_ORIENT',
       'KENYA_RE', 'KENYAN_ALLIANCE', 'LION_OF_KENYA', 'MADISON', 'MAYFAIR',
       'MER_CANTILE'],
      dtype='object')
Index(['NO.', 'UNNAMED:_1', 'OCCIDENTAL', 'PACIS', 'PHOENIX', 'PIONEER',
       'REAL', 'TAUSI', 'THE_MONARCH', 'TRIDENT', 'UAP_IN_SURANCE', 'TOTAL'],
      dtype='object')

In [171]:
new_df4.to_csv("General_BS_10.csv")

# 2011

In [72]:
files4= ["IRA ANNUAL REPORT 2011 FINAL.xlsx"]
pages4=[["Table 31","Table 33"]]
c=1
Gen_BS_2011_1= pd.DataFrame()
for fil4,page in zip(files4,pages4):
    f4 = pd.ExcelFile(fil4)
    ## reading the specific sheets
    for p in page:
        try:
            sheet=  pd.read_excel(f4,p,header=1)
            sheet.columns=sheet.columns.str.upper()
            
            sheet.set_index("ITEM",inplace=True)
            sheet_t = sheet.T
            sheet_t.columns = sheet_t.columns.str.strip()
            sheet_t.columns = sheet_t.columns.str.replace('\n',' ')
            sheet_t.columns = sheet_t.columns.str.replace(' ','_')
            sheet_t.columns = sheet_t.columns.str.replace('__','_')
            sheet_t.columns = sheet_t.columns.str.upper()
            sheet_t.index = sheet_t.index.str.replace('\n',' ')
            sheet_t.index = sheet_t.index.str.replace(' ','_')
            sheet_t.index = sheet_t.index.str.replace('__','_')
            #print(sheet_t.head())
            Gen_BS_2011_1 = pd.concat([Gen_BS_2011_1,sheet_t])
        except( KeyError, IndexError)as e:
            sheet=  pd.read_excel(f4,p,header=2)
            sheet.columns=sheet.columns.str.upper()
            sheet.set_index("ITEM",inplace=True)
            sheet_t = sheet.T
            sheet_t.columns = sheet_t.columns.str.strip()
            sheet_t.index = sheet_t.index.str.replace('-',' ')
            sheet_t.columns = sheet_t.columns.str.replace('\n',' ')
            sheet_t.columns = sheet_t.columns.str.replace(' ','_')
            sheet_t.columns = sheet_t.columns.str.replace('__','_')
            sheet_t.columns = sheet_t.columns.str.upper()
            sheet_t.index = sheet_t.index.str.replace('-',' ')
            sheet_t.index = sheet_t.index.str.replace('\n',' ')
            sheet_t.index = sheet_t.index.str.replace(' ','_')
            sheet_t.index = sheet_t.index.str.replace('__','_')
            Gen_BS_2011_1 = pd.concat([Gen_BS_2011_1,sheet_t])
            #print(sheet_t.head())
        print(sheet_t.columns)

Index(['NOMINAL_SHARE_CAPITAL', 'NOMINAL_VALUE_OF_UNISSUED_SHARE_CAPITAL',
       'ISSUED_SHARE_CAPITAL', 'PAID-UP_CAPITAL', 'GENERAL_RESERVE',
       'INVESTMENT_FLUCTUATION_RESERVE', 'UNAPPRTD_SURPLUS/RETAINED_EARNINGS',
       'ALL_OTHER_RESERVES', 'TOTAL_PAID-UP_CAPITAL_&_RESERVES',
       'UNDERWRITING_PROVISIONS', 'LONG_TERM_LIABILITIES',
       'CURRENT_LIABLITIES', 'TOTAL_PAID-UP_CAPITAL,_RES_ERVES_&_LIABILITIES',
       'LAND_&_BUILDINGS', 'INVESTMENT_PROPERTY', 'OTHER_FIXED_ASSETS',
       'KENYA_GOVT._SECURITIES', 'LOCAL_GOVT._AUTHORITY_SECURITIES',
       'OTHER_SECURITIES', 'DEBENTURES_(QUOTED_&_UNQUOTED)',
       'PREFERENCE_SHARES_(QUOTED_&_UNQUOTED)', 'INVESTMENT_IN_SUBSIDIARY',
       'QUOTED_ORDINARY_SHARES', 'UNQUOTED_ORDINARY_SHARES',
       'SECURED_LOANS_(INCLUDING_LOAN_OF_POLICIES)', 'UNSECURED_LOANS',
       'DEPOSITS_(WITH_BANKS_&_OTHER_INSTITUTIONS)', 'OTHER_INVESTMENTS',
       'OUTSTANDING_PREMIUMS', 'AMOUNTS_DUE_FROM_RE-INSURERS', 'CASH',
       'OTHER_CURRENT_ASSETS', 'INTANGIBLE_ASSETS', 'TOTAL_ASSETS',
       'AMOUNTS_IN_'000'_KES'],
      dtype='object', name='ITEM')
Index(['NOMINAL_SHARE_CAPITAL', 'NOMINAL_VALUE_OF_UNISSUED_SHARE_CAPITAL',
       'ISSUED_SHARE_CAPITAL', 'PAID-UP_CAPITAL', 'GENERAL_RESERVE',
       'INVESTMENT_FLUCTUATION_RESERVE', 'UNAPPRTD_SURPLUS/RETAINED_EARNINGS',
       'ALL_OTHER_RESERVES', 'TOTAL_PAID-UP_CAPITAL_&_RESERVES',
       'UNDERWRITING_PROVISIONS', 'LONG_TERM_LIABILITIES',
       'CURRENT_LIABLITIES', 'TOTAL_PAID-UP_CAPITAL,_RES_ERVES_&_LIABILITIES',
       'LAND_&_BUILDINGS', 'INVESTMENT_PROPERTY', 'OTHER_FIXED_ASSETS',
       'KENYA_GOVT._SECURITIES', 'LOCAL_GOVT._AUTHORITY_SECURITIES',
       'OTHER_SECURITIES', 'DEBENTURES_(QUOTED_&_UNQUOTED)',
       'PREFERENCE_SHARES_(QUOTED_&_UNQUOTED)', 'INVESTMENT_IN_SUBSIDIARY',
       'QUOTED_ORDINARY_SHARES', 'UNQUOTED_ORDINARY_SHARES',
       'SECURED_LOANS_(INCLUDING_LOAN_OF_POLICIES)', 'UNSECURED_LOANS',
       'DEPOSITS_(WITH_BANKS_&_OTHER_INSTITUTIONS)', 'OTHER_INVESTMENTS',
       'OUTSTANDING_PREMIUMS', 'AMOUNTS_DUE_FROM_RE-INSURERS', 'CASH',
       'OTHER_CURRENT_ASSETS', 'INTANGIBLE_ASSETS', 'TOTAL_ASSETS',
       'AMOUNTS_IN_'000'_KES'],
      dtype='object', name='ITEM')

In [74]:
Gen_BS_2011_1.to_csv("Gen_BS_2011_1.csv")

In [76]:
files4= ["IRA ANNUAL REPORT 2011 FINAL.xlsx"]
pages4=[["Table 32"]]
c=1
Gen_BS_2011_2= pd.DataFrame()
for fil4,page in zip(files4,pages4):
    f4 = pd.ExcelFile(fil4)
    ## reading the specific sheets
    for p in page:
        try:
            sheet=  pd.read_excel(f4,p,header=1)
            sheet.columns=sheet.columns.str.upper()
            
            sheet.set_index("ITEM",inplace=True)
            sheet_t = sheet.T
            sheet_t.columns = sheet_t.columns.str.strip()
            sheet_t.columns = sheet_t.columns.str.replace('\n',' ')
            sheet_t.columns = sheet_t.columns.str.replace(' ','_')
            sheet_t.columns = sheet_t.columns.str.replace('__','_')
            sheet_t.columns = sheet_t.columns.str.upper()
            sheet_t.index = sheet_t.index.str.replace('\n',' ')
            sheet_t.index = sheet_t.index.str.replace(' ','_')
            sheet_t.index = sheet_t.index.str.replace('__','_')
            #print(sheet_t.head())
            Gen_BS_2011_2 = pd.concat([Gen_BS_2011_2,sheet_t])
        except( KeyError, IndexError)as e:
            sheet=  pd.read_excel(f4,p,header=2)
            sheet.columns=sheet.columns.str.upper()
            sheet.set_index("ITEM",inplace=True)
            sheet_t = sheet.T
            sheet_t.columns = sheet_t.columns.str.strip()
            sheet_t.index = sheet_t.index.str.replace('-',' ')
            sheet_t.columns = sheet_t.columns.str.replace('\n',' ')
            sheet_t.columns = sheet_t.columns.str.replace(' ','_')
            sheet_t.columns = sheet_t.columns.str.replace('__','_')
            sheet_t.columns = sheet_t.columns.str.upper()
            sheet_t.index = sheet_t.index.str.replace('-',' ')
            sheet_t.index = sheet_t.index.str.replace('\n',' ')
            sheet_t.index = sheet_t.index.str.replace(' ','_')
            sheet_t.index = sheet_t.index.str.replace('__','_')
            Gen_BS_2011_2 = pd.concat([Gen_BS_2011_2,sheet_t])
            #print(sheet_t.head())
        print(sheet_t.columns)

Index([                         'NOMINAL_SHARE_CAPITAL',
              'NOMINAL_VALUE_OF_UNISSUED_SHARE_CAPITAL',
                                 'ISSUED_SHARE_CAPITAL',
                                      'PAID-UP_CAPITAL',
                                      'GENERAL_RESERVE',
                       'INVESTMENT_FLUCTUATION_RESERVE',
                   'UNAPPRTD_SURPLUS/RETAINED_EARNINGS',
                                   'ALL_OTHER_RESERVES',
                     'TOTAL_PAID-UP_CAPITAL_&_RESERVES',
                              'UNDERWRITING_PROVISIONS',
                                'LONG_TERM_LIABILITIES',
                                   'CURRENT_LIABLITIES',
       'TOTAL_PAID-UP_CAPITAL,_RES_ERVES_&_LIABILITIES',
                                     'LAND_&_BUILDINGS',
                                  'INVESTMENT_PROPERTY',
                                   'OTHER_FIXED_ASSETS',
                               'KENYA_GOVT._SECURITIES',
                     'LOCAL_GOVT._AUTHORITY_SECURITIES',
                                     'OTHER_SECURITIES',
                       'DEBENTURES_(QUOTED_&_UNQUOTED)',
                'PREFERENCE_SHARES_(QUOTED_&_UNQUOTED)',
                             'INVESTMENT_IN_SUBSIDIARY',
                               'QUOTED_ORDINARY_SHARES',
                             'UNQUOTED_ORDINARY_SHARES',
           'SECURED_LOANS_(INCLUDING_LOAN_OF_POLICIES)',
                                      'UNSECURED_LOANS',
           'DEPOSITS_(WITH_BANKS_&_OTHER_INSTITUTIONS)',
                                    'OTHER_INVESTMENTS',
                                 'OUTSTANDING_PREMIUMS',
                         'AMOUNTS_DUE_FROM_RE-INSURERS',
                                                 'CASH',
                                 'OTHER_CURRENT_ASSETS',
                                    'INTANGIBLE_ASSETS',
                                         'TOTAL_ASSETS',
                                 'AMOUNTS_IN_'000'_KES',
                                                    nan,
                                                    nan,
                                                    nan,
                                                    nan,
                                                    nan],
      dtype='object', name='ITEM')

In [79]:
Gen_BS_2011_2.to_csv("Gen_BS_2011_2.csv")

In [80]:
files4= ["IRA ANNUAL REPORT 2011 FINAL.xlsx"]
pages4=[["Table 34"]]
c=1
Gen_BS_2011_3= pd.DataFrame()
for fil4,page in zip(files4,pages4):
    f4 = pd.ExcelFile(fil4)
    ## reading the specific sheets
    for p in page:
        try:
            sheet=  pd.read_excel(f4,p,header=1)
            sheet.columns=sheet.columns.str.upper()
            
            sheet.set_index("ITEM",inplace=True)
            sheet_t = sheet.T
            sheet_t.columns = sheet_t.columns.str.strip()
            sheet_t.columns = sheet_t.columns.str.replace('\n',' ')
            sheet_t.columns = sheet_t.columns.str.replace(' ','_')
            sheet_t.columns = sheet_t.columns.str.replace('__','_')
            sheet_t.columns = sheet_t.columns.str.upper()
            sheet_t.index = sheet_t.index.str.replace('\n',' ')
            sheet_t.index = sheet_t.index.str.replace(' ','_')
            sheet_t.index = sheet_t.index.str.replace('__','_')
            #print(sheet_t.head())
            Gen_BS_2011_3 = pd.concat([Gen_BS_2011_3,sheet_t])
        except( KeyError, IndexError)as e:
            sheet=  pd.read_excel(f4,p,header=2)
            sheet.columns=sheet.columns.str.upper()
            sheet.set_index("ITEM",inplace=True)
            sheet_t = sheet.T
            sheet_t.columns = sheet_t.columns.str.strip()
            sheet_t.index = sheet_t.index.str.replace('-',' ')
            sheet_t.columns = sheet_t.columns.str.replace('\n',' ')
            sheet_t.columns = sheet_t.columns.str.replace(' ','_')
            sheet_t.columns = sheet_t.columns.str.replace('__','_')
            sheet_t.columns = sheet_t.columns.str.upper()
            sheet_t.index = sheet_t.index.str.replace('-',' ')
            sheet_t.index = sheet_t.index.str.replace('\n',' ')
            sheet_t.index = sheet_t.index.str.replace(' ','_')
            sheet_t.index = sheet_t.index.str.replace('__','_')
            Gen_BS_2011_3 = pd.concat([Gen_BS_2011_3,sheet_t])
            #print(sheet_t.head())
        print(sheet_t.columns)

Index([                         'NOMINAL_SHARE_CAPITAL',
              'NOMINAL_VALUE_OF_UNISSUED_SHARE_CAPITAL',
                                 'ISSUED_SHARE_CAPITAL',
                                      'PAID-UP_CAPITAL',
                                      'GENERAL_RESERVE',
                       'INVESTMENT_FLUCTUATION_RESERVE',
                   'UNAPPRTD_SURPLUS/RETAINED_EARNINGS',
                                   'ALL_OTHER_RESERVES',
                     'TOTAL_PAID-UP_CAPITAL_&_RESERVES',
                              'UNDERWRITING_PROVISIONS',
                                'LONG_TERM_LIABILITIES',
                                   'CURRENT_LIABLITIES',
       'TOTAL_PAID-UP_CAPITAL,_RES_ERVES_&_LIABILITIES',
                                     'LAND_&_BUILDINGS',
                                  'INVESTMENT_PROPERTY',
                                   'OTHER_FIXED_ASSETS',
                               'KENYA_GOVT._SECURITIES',
                     'LOCAL_GOVT._AUTHORITY_SECURITIES',
                                     'OTHER_SECURITIES',
                       'DEBENTURES_(QUOTED_&_UNQUOTED)',
                'PREFERENCE_SHARES_(QUOTED_&_UNQUOTED)',
                             'INVESTMENT_IN_SUBSIDIARY',
                               'QUOTED_ORDINARY_SHARES',
                             'UNQUOTED_ORDINARY_SHARES',
           'SECURED_LOANS_(INCLUDING_LOAN_OF_POLICIES)',
                                      'UNSECURED_LOANS',
           'DEPOSITS_(WITH_BANKS_&_OTHER_INSTITUTIONS)',
                                    'OTHER_INVESTMENTS',
                                 'OUTSTANDING_PREMIUMS',
                         'AMOUNTS_DUE_FROM_RE-INSURERS',
                                                 'CASH',
                                 'OTHER_CURRENT_ASSETS',
                                    'INTANGIBLE_ASSETS',
                                         'TOTAL_ASSETS',
                                 'AMOUNTS_IN_'000'_KES',
                                                    nan,
                                                    nan],
      dtype='object', name='ITEM')

In [81]:
Gen_BS_2011_3.to_csv("Gen_BS_2011_3.csv")

## P/L for Gen Insurance

## 2019-2017

In [7]:
files= ["2019 Annual Insurance Industry Statistics.xlsm","2018 Annual Statistics 28062019.xls","2017-Annual-Insurance-Statistics-Uploaded.xlsm"]
p_l_gen_19_17= pd.DataFrame()
c=0
for fil in files:
    c+=1
    f1 = pd.ExcelFile(fil)
    ## reading the specific sheets
    sheet1= pd.read_excel(f1,"APPENDIX 1",header=2)
    ### dropping the unnamed column
    sheet1.drop("Unnamed: 0",axis=1,inplace=True)
    ### concatinating the data sheets
    p_l_gen_19_17 = pd.concat([p_l_gen_19_17,sheet1])

In [9]:
p_l_gen_19_17.to_csv("p_l_gen_19_17.csv")

## 2016-2013

In [180]:
files2= ["Annual-_Industry_Report_2016.xlsx","Annual Report 2015.xlsx","Annual-Report-2014-12.10.2015-Final.xlsx","Latest 2013 IRA Annual Report.xlsx"]
pages=[["Table 60"],["Table 56"],["Table 29"],["Table 33"]]
p_l_gen_16_13= pd.DataFrame()
for filz,page in zip(files2,pages):
    f2 = pd.ExcelFile(filz)
    ## reading the specific sheets
    for p in page:
        sheet=  pd.read_excel(f2,p,header=1)
        sheet.columns=sheet.columns.str.upper()
        sheet_t = sheet
        sheet_t.columns = sheet_t.columns.str.strip()
        p_l_gen_16_13 = pd.concat([p_l_gen_16_13,sheet_t])

In [182]:
p_l_gen_16_13.to_csv("p_l_gen_16_13.csv")

# 2009 - 2006

In [183]:
files3= ["Annual_Report_Year_2006.xlsx","2007 Annual Report.xlsx","2009 Annual Report.xlsx"]
pages3=[["Table 30"],["Table 37"],["Table 37"]]
c=1
p_l_gen_09_06= pd.DataFrame()
for fil3,page in zip(files3,pages3):
    f3 = pd.ExcelFile(fil3)
    ## reading the specific sheets
    for p in page:
        try:
            sheet=  pd.read_excel(f3,p,header=1)
            sheet.columns=sheet.columns.str.upper()
            
            sheet.set_index("NAME OF INSURER",inplace=True)
            sheet_t = sheet
            sheet_t.columns = sheet_t.columns.str.strip()
            sheet_t.columns = sheet_t.columns.str.replace('\n',' ')
            sheet_t.columns = sheet_t.columns.str.replace(' ','_')
            sheet_t.columns = sheet_t.columns.str.replace('__','_')
            sheet_t.columns = sheet_t.columns.str.upper()
            p_l_gen_09_06 = pd.concat([p_l_gen_09_06,sheet_t])
        except KeyError:
            sheet=  pd.read_excel(f3,p,header=3)
            # sheet.columns=sheet.columns.str.upper()
            #sheet.set_index("NAME OF INSURER",inplace=True)
            # sheet_t = sheet
            sheet_t.columns = sheet_t.columns.str.strip()
            sheet_t.columns = sheet_t.columns.str.replace('\n',' ')
            sheet_t.columns = sheet_t.columns.str.replace(' ','_')
            sheet_t.columns = sheet_t.columns.str.replace('__','_')
            sheet_t.columns = sheet_t.columns.str.upper()
            p_l_gen_09_06 = pd.concat([p_l_gen_09_06,sheet_t])
            
        print(sheet_t.columns)

Index(['COMPANY', 'PROFIT_TRANSFERRED_FROM_REVENUE', 'INVESTMENT_INCOME',
       'OTHER_INCOME', 'TOTAL_INCOME', 'LOSS_TRANSFERRED_FROM_REVENUE',
       'MANAGEMENT_EXPENSES', 'TOTAL_OUTGO', 'PROFIT_/_(LOSS)_BEFORE_TAXATION',
       'PROVISION_FOR_TAXATION', 'PROFIT/(LOSS)_AFTER_TAXATION',
       'UNAPPROPRI-_ATED_PROFIT/_(LOSS)_BF', 'TRANSFER_TO_RESERVES',
       'OTHER_APPROPRIA-_TIONS', 'DIVIDEND',
       'UNAPPROPRIATED_PROFIT_/_(LOSS)_CF'],
      dtype='object')
Index(['COMPANY', 'PROFIT_TRANSFERRED_FROM_REVENUE', 'INVESTMENT_INCOME',
       'OTHER_INCOME', 'TOTAL_INCOME', 'LOSS_TRANSFERRED_FROM_REVENUE',
       'MANAGEMENT_EXPENSES', 'TOTAL_OUTGO', 'PROFIT_/_(LOSS)_BEFORE_TAXATION',
       'PROVISION_FOR_TAXATION', 'PROFIT/(LOSS)_AFTER_TAXATION',
       'UNAPPROPRI-_ATED_PROFIT/_(LOSS)_BF', 'TRANSFER_TO_RESERVES',
       'OTHER_APPROPRIA-_TIONS', 'DIVIDEND',
       'UNAPPROPRIATED_PROFIT_/_(LOSS)_CF'],
      dtype='object')
Index(['COMPANY', 'PROFIT_TRANSFERRED_FROM_REVENUE', 'INVESTMENT_INCOME',
       'OTHER_INCOME', 'TOTAL_INCOME', 'LOSS_TRANSFERRED_FROM_REVENUE',
       'MANAGEMENT_EXPENSES', 'TOTAL_OUTGO', 'PROFIT_/_(LOSS)_BEFORE_TAXATION',
       'PROVISION_FOR_TAXATION', 'PROFIT/(LOSS)_AFTER_TAXATION',
       'UNAPPROPRI-_ATED_PROFIT/_(LOSS)_BF', 'TRANSFER_TO_RESERVES',
       'OTHER_APPROPRIA-_TIONS', 'DIVIDEND',
       'UNAPPROPRIATED_PROFIT_/_(LOSS)_CF'],
      dtype='object')

In [185]:
p_l_gen_09_06.to_csv("p_l_gen_09_06.csv")